### ISSUE TITLE
Requirement of GPU

### ISSUE THREAD

**Issue by Hugo-cell111** [kunzhan/DSSN#1]
Hi! May I ask how many GPUs and what kind of GPU are needed in your work? Thanks!

**Comment by zhibotian** [comment]
Thank you for your interest in our work. For Pacal VOC 2012, we employed 4 NVIDIA RTX 3090 GPUs for both ResNet50 and ResNet101 models. In the case of Cityscapes, 4 NVIDIA RTX 3090 GPUs were used for ResNet50, whereas ResNet101 required 8 NVIDIA RTX 3090 GPUs. Further details can be found through the run bash scripts available at https://github.com/kunzhan/DSSN/blob/efaee86d3c023abc6b72dcda22ab1017ff71f1d4/voc/scripts/train.sh#L20 or from the output log files at https://github.com/kunzhan/DSSN/blob/efaee86d3c023abc6b72dcda22ab1017ff71f1d4/voc/exp/pascal/DSSN/r101/1_16/20230416_102707.log#L19

**Comment by Hugo-cell111** [comment]
Thanks!
