### ISSUE TITLE
Question about the difference between cityscapes and pascal voc of the code

### ISSUE THREAD

**Issue by Hugo-cell111** [kunzhan/DSSN#2]
Hi! May I ask why you set two different folders of two dataset? I think they can share the same code under two dataset settings. Thanks!

**Comment by kunzhan** [comment]
In PyTorch 2.0, the speed on Cityscapes is a bit faster. We have already run the experiments on VOC, so we haven't re-run them in 2.0.

**Comment by Hugo-cell111** [comment]
Thanks!
