### ISSUE TITLE
What's the difference between your work and unimatch?

### ISSUE THREAD

**Issue by YinqiCai** [kunzhan/DSSN#5]
I found your code is almost the same as unimatch, but you don't cite unimatch.

**Comment by zhibotian** [comment]
Thank you for your interest in our work. It appears that you may have accessed the preliminary version available on arXiv. To view the updated and camera-ready edition, please refer to the following link: [https://dl.acm.org/doi/10.1145/3581783.3611816](https://dl.acm.org/doi/10.1145/3581783.3611816).

**Comment by YinqiCai** [comment]
> Thank you for your interest in our work. It appears that you may have accessed the preliminary version available on arXiv. To view the updated and camera-ready edition, please refer to the following link: https://dl.acm.org/doi/10.1145/3581783.3611816.

I got it. Thanks for your quick reply.
