### ISSUE TITLE
Question about the Pascal blender 1_2 split

### ISSUE THREAD

**Issue by Hugo-cell111** [kunzhan/DSSN#7]
Hi! Could you please provide the Pascal blender 1_2 split? I can only see 1_16, 1_8, 1_4 splits of Pascal blender dataset.

**Comment by kunzhan** [comment]
[labeled.txt](https://github.com/kunzhan/DSSN/files/14229422/labeled.txt)
[unlabeled.txt](https://github.com/kunzhan/DSSN/files/14229423/unlabeled.txt)

**Comment by Hugo-cell111** [comment]
Thank you so much! Happy New Year and wish you a joyful Lunar New Year!
